#!/bin/sh
# agmsg gh owner guard PATH helper
#
# This file is sourced by interactive Bash and Zsh startup files. Keep the
# directory comparison exact: an empty PATH entry and every other entry retain
# their original order after the managed directory is prepended.

AGMSG_GH_OWNER_GUARD_PATH_BIN="$HOME/.agents/bin"
AGMSG_GH_OWNER_GUARD_PATH_REST="${PATH-}"
AGMSG_GH_OWNER_GUARD_PATH_NEW=""
AGMSG_GH_OWNER_GUARD_PATH_HAVE_NEW=0

while :; do
  case "$AGMSG_GH_OWNER_GUARD_PATH_REST" in
    *:*)
      AGMSG_GH_OWNER_GUARD_PATH_ENTRY="${AGMSG_GH_OWNER_GUARD_PATH_REST%%:*}"
      AGMSG_GH_OWNER_GUARD_PATH_REST="${AGMSG_GH_OWNER_GUARD_PATH_REST#*:}"
      AGMSG_GH_OWNER_GUARD_PATH_MORE=1
      ;;
    *)
      AGMSG_GH_OWNER_GUARD_PATH_ENTRY="$AGMSG_GH_OWNER_GUARD_PATH_REST"
      AGMSG_GH_OWNER_GUARD_PATH_REST=""
      AGMSG_GH_OWNER_GUARD_PATH_MORE=0
      ;;
  esac

  if [ "$AGMSG_GH_OWNER_GUARD_PATH_ENTRY" != "$AGMSG_GH_OWNER_GUARD_PATH_BIN" ]; then
    if [ "$AGMSG_GH_OWNER_GUARD_PATH_HAVE_NEW" -eq 0 ]; then
      AGMSG_GH_OWNER_GUARD_PATH_NEW="$AGMSG_GH_OWNER_GUARD_PATH_ENTRY"
      AGMSG_GH_OWNER_GUARD_PATH_HAVE_NEW=1
    else
      AGMSG_GH_OWNER_GUARD_PATH_NEW="$AGMSG_GH_OWNER_GUARD_PATH_NEW:$AGMSG_GH_OWNER_GUARD_PATH_ENTRY"
    fi
  fi

  [ "$AGMSG_GH_OWNER_GUARD_PATH_MORE" -eq 1 ] || break
done

PATH="$AGMSG_GH_OWNER_GUARD_PATH_BIN"
if [ "$AGMSG_GH_OWNER_GUARD_PATH_HAVE_NEW" -eq 1 ]; then
  PATH="$PATH:$AGMSG_GH_OWNER_GUARD_PATH_NEW"
fi
export PATH

unset AGMSG_GH_OWNER_GUARD_PATH_BIN \
  AGMSG_GH_OWNER_GUARD_PATH_REST \
  AGMSG_GH_OWNER_GUARD_PATH_NEW \
  AGMSG_GH_OWNER_GUARD_PATH_HAVE_NEW \
  AGMSG_GH_OWNER_GUARD_PATH_ENTRY \
  AGMSG_GH_OWNER_GUARD_PATH_MORE
